"use client";

import { useCallback, useEffect, useState } from "react";
import { InsightFeedback } from "./FeedbackButtons";
import EvidenceList, { type Evidence } from "./EvidenceDrawer";
import { labelStyles, sectionStyles } from "./ui";

type BuyerQuestion = {
  question: string;
  intent: string;
  audience: string;
  evidence: Evidence[];
};

type State =
  | { kind: "loading" }
  | { kind: "none" }
  | { kind: "loaded"; questions: BuyerQuestion[]; model: string }
  | { kind: "error"; message: string };

export default function BuyerQuestionsSection({
  projectId,
  initial,
}: {
  projectId: number;
  /** undefined = not fetched yet, null = confirmed none, object = data */
  initial?: { questions: BuyerQuestion[]; model: string } | null;
}) {
  const [state, setState] = useState<State>(
    initial === undefined
      ? { kind: "loading" }
      : initial === null || initial.questions.length === 0
        ? { kind: "none" }
        : { kind: "loaded", questions: initial.questions, model: initial.model },
  );

  const load = useCallback(async () => {
    try {
      const res = await fetch(`/api/v1/projects/${projectId}/buyer-questions`, {
        cache: "no-store",
      });
      if (res.status === 404) {
        setState({ kind: "none" });
        return;
      }
      if (!res.ok) throw new Error(`Backend responded with ${res.status}`);
      const data = await res.json();
      const questions: BuyerQuestion[] = data.result?.questions ?? [];
      setState(
        questions.length === 0
          ? { kind: "none" }
          : { kind: "loaded", questions, model: data.model },
      );
    } catch (err) {
      setState({
        kind: "error",
        message: err instanceof Error ? err.message : "Request failed",
      });
    }
  }, [projectId]);

  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect -- load() is async; state updates happen after await, never synchronously.
    if (initial === undefined) load();
    window.addEventListener("analysis-completed", load);
    window.addEventListener("analysis-failed", load);
    return () => {
      window.removeEventListener("analysis-completed", load);
      window.removeEventListener("analysis-failed", load);
    };
  }, [initial, load]);

  return (
    <section style={sectionStyles} aria-label="Buyer Questions">
      <h2 style={{ fontSize: 18, marginBottom: 4, color: "#111827" }}>
        Buyer Questions
      </h2>

      {state.kind === "loading" && (
        <p style={{ fontSize: 14, color: "#6b7280" }} role="status">
          Loading buyer questions…
        </p>
      )}

      {state.kind === "none" && (
        <p style={{ fontSize: 14, color: "#6b7280" }}>
          No buyer questions yet — run <strong>Analyze</strong> to generate them.
        </p>
      )}

      {state.kind === "error" && (
        <p style={{ fontSize: 14, color: "#dc2626" }} role="alert">
          Failed to load buyer questions: {state.message}
        </p>
      )}

      {state.kind === "loaded" && (
        <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
          {state.questions.map((q) => (
            <div
              key={q.question}
              style={{
                border: "1px solid #e5e7eb",
                borderRadius: 8,
                background: "white",
                padding: "12px 16px",
              }}
            >
              <strong style={{ fontSize: 15, color: "#111827" }}>
                {q.question}
              </strong>

              <div style={{ marginTop: 8 }}>
                <div style={labelStyles}>Intent</div>
                <p style={{ margin: 0, fontSize: 14, color: "#374151" }}>
                  {q.intent}
                </p>
              </div>

              <div style={{ marginTop: 8 }}>
                <div style={labelStyles}>Audience</div>
                <p style={{ margin: 0, fontSize: 14, color: "#374151" }}>
                  {q.audience}
                </p>
              </div>

              <div style={{ marginTop: 8 }}>
                <div style={labelStyles}>Evidence</div>
                <EvidenceList evidence={q.evidence} />
              </div>
            </div>
          ))}

          <div
            style={{
              display: "flex",
              justifyContent: "space-between",
              alignItems: "center",
              gap: 8,
              flexWrap: "wrap",
            }}
          >
            <span style={{ fontSize: 11, color: "#9ca3af" }}>
              Generated by {state.model}
            </span>
            <InsightFeedback
              projectId={projectId}
              entityType="buyer_questions"
              entityRef="Buyer Questions"
            />
          </div>
        </div>
      )}
    </section>
  );
}
