"""add project website_url and description

Revision ID: 69d4ce3eb435
Revises: e3150f45ee9b
Create Date: 2026-09-24 12:15:47.266763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69d4ce3eb435'
down_revision: Union[str, Sequence[str], None] = 'e3150f45ee9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('website_url', sa.String(length=2000), nullable=False))
    op.add_column('projects', sa.Column('description', sa.String(length=2000), nullable=True))
    op.alter_column('projects', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('projects_user_id_fkey'), 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('projects_user_id_fkey'), 'projects', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('projects', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('projects', 'description')
    op.drop_column('projects', 'website_url')
    # ### end Alembic commands ###
