"""create competitors table

Revision ID: dea12a58c640
Revises: 92997cb60c3c
Create Date: 2026-09-24 12:57:55.467309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dea12a58c640'
down_revision: Union[str, Sequence[str], None] = '92997cb60c3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('reason_relevant', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('competitors')
    # ### end Alembic commands ###
